Repository oubaydos/javaRIG, pull requests merged in 2022-12, with the labels that each got.

#28 Javadocs for interfaces and abstract calsses
  src/main/java/io/javarig/TypeEnum.java
  src/main/java/io/javarig/exception/InstanceGenerationException.java
  src/main/java/io/javarig/exception/InvalidGenericParametersNumberException.java
  src/main/java/io/javarig/exception/NewInstanceCreationException.java
  src/main/java/io/javarig/exception/NoFieldAssociatedToSetter.java
  src/main/java/io/javarig/generator/AbstractTypeGenerator.java
  src/main/java/io/javarig/generator/CollectionGenerator.java
  src/main/java/io/javarig/generator/EnumGenerator.java
  src/main/java/io/javarig/generator/GenericTypeGenerator.java
  src/main/java/io/javarig/generator/ObjectGenerator.java
  src/main/java/io/javarig/generator/TypeBasedGenerator.java
  src/main/java/io/javarig/generator/TypeGenerator.java
  src/main/java/io/javarig/generator/list/ListGenerator.java
  src/main/java/io/javarig/generator/map/MapGenerator.java
  src/main/java/io/javarig/util/Utils.java
  src/test/java/io/javarig/RandomInstanceGeneratorTest.java
  src/test/java/io/javarig/generator/FakeList.java
  src/test/java/io/javarig/generator/FakeMap.java
  src/test/java/io/javarig/generator/ListGeneratorTest.java
  src/test/java/io/javarig/generator/MapGeneratorTest.java
  src/test/java/io/javarig/testclasses/ClassWithDefaultConstructorThrowingException.java
Labels: documentation

#29 added ClassWithPrivateSetter test
  src/main/java/io/javarig/generator/ObjectGenerator.java
  src/test/java/io/javarig/RandomInstanceGeneratorTest.java
  src/test/java/io/javarig/testclasses/ClassWithPrivateSetter.java
Labels: test

#31 renamed a test method and removed unused class
  src/main/java/io/javarig/exception/NoFieldAssociatedToSetter.java
  src/test/java/io/javarig/RandomInstanceGeneratorTest.java
  src/test/java/io/javarig/testclasses/ClassWithPrivateSetter.java
  src/test/java/io/javarig/testclasses/ClassWithSomeNonPublicSetters.java
Labels: test

#37 add validators in RandomInstanceGenerator
  .gitignore
  pom.xml
  src/main/java/io/javarig/RandomInstanceGenerator.java
  src/main/java/io/javarig/TypeEnum.java
  src/main/java/io/javarig/generator/ObjectGenerator.java
  src/main/java/io/javarig/generator/collection/SingleGenericTypeCollectionGenerator.java
  src/main/java/io/javarig/generator/collection/map/MapGenerator.java
  src/test/java/io/javarig/RandomInstanceGeneratorTest.java
  target/classes/logback.xml
Labels: enhancement

#40 refactored tests
  src/test/java/io/javarig/RandomInstanceGeneratorTest.java
  src/test/java/io/javarig/generation/ObjectGenerationTest.java
  src/test/java/io/javarig/generation/javapredefinedtypes/ArrayGenerationTest.java
  src/test/java/io/javarig/generation/javapredefinedtypes/DateTimeGenerationTest.java
  src/test/java/io/javarig/generation/javapredefinedtypes/EnumGenerationTest.java
  src/test/java/io/javarig/generation/javapredefinedtypes/StringGenerationTest.java
  src/test/java/io/javarig/generation/javapredefinedtypes/WrappersGenerationTest.java
  src/test/java/io/javarig/generation/javapredefinedtypes/collection/CollectionGenerationTest.java
  src/test/java/io/javarig/generation/javapredefinedtypes/collection/ListGenerationTest.java
  src/test/java/io/javarig/generation/javapredefinedtypes/collection/MapGenerationTest.java
  src/test/java/io/javarig/generator/ListGeneratorTest.java
  src/test/java/io/javarig/generator/MapGeneratorTest.java
  src/test/java/io/javarig/testclasses/FakeList.java
  src/test/java/io/javarig/testclasses/FakeMap.java
Labels: enhancement

#42 removed unused code
  README.md
  src/main/java/io/javarig/TypeGeneratorFactory.java
  src/main/java/io/javarig/exception/NewInstanceCreationException.java
  src/main/java/io/javarig/generator/ByteArrayGenerator.java
Labels: enhancement
